### ISSUE TITLE
Errors after baselines repo latest commit

### ISSUE THREAD

**Issue by arturdulewicz** [chris-chris/pysc2-examples#12]
After cleanups done in baselines repo I am getting new errors while running `train_mineral_shards` (with `enjoy_mineral_shards` everything works just fine)

```
Traceback (most recent call last):
  File "C:/Users/Artur/Documents/PySC2/train/train_mineral_shards.py", line 14, in <module>
    from a2c.policies import CnnPolicy
  File "C:\Users\Artur\Documents\PySC2\train\a2c\policies.py", line 3, in <module>
    from baselines.acktr.utils import conv, fc, dense, conv_to_fc, sample, kl_div
ImportError: cannot import name 'conv'

Process finished with exit code 1
```

Any help?

**Comment by rwill128** [comment]
I'm encountering the same issue, no progress yet.

**Comment by brean** [comment]
Same here. Seems baselines changed their API. conv now only has dense and kl_div (see [current utils.py]( https://github.com/openai/baselines/blob/master/baselines/acktr/utils.py) and [this commit where it was deleted](https://github.com/openai/baselines/commit/9fa8e1baf1d1f975b87b369a8082122eac812eb1#diff-a676fdf2cd7ef15a377b4a0319c533fa) ). I think [baselines.a2c.utils](https://github.com/openai/baselines/blob/d9b36601d94368f560c8830e1458d22e2881d61f/baselines/a2c/utils.py#L42) can be used instead because it seems to be a duplicate.
If you like I can provide a pull request.
