### ISSUE TITLE
Not sure if incompatible with baselines or bad baselines installation

### ISSUE THREAD

**Issue by rwill128** [chris-chris/pysc2-examples#13]
I'm getting the following error when I run enjoy_mineral_shards. I didn't exactly have a seamless baselines installation, but I think baselines is installed correctly now and not the problem.

> C:\Users\Rick\Desktop\pysc2-examples>python enjoy_mineral_shards.py
Traceback (most recent call last):
  File "enjoy_mineral_shards.py", line 162, in <module>
    main()
  File "enjoy_mineral_shards.py", line 55, in main
    "mineral_shards.pkl", act_params=act_params)
  File "C:\Users\Rick\Desktop\pysc2-examples\deepq_mineral_shards.py", line 93, in load
    return ActWrapper.load(path, num_cpu=num_cpu, act_params=act_params)
  File "C:\Users\Rick\Desktop\pysc2-examples\deepq_mineral_shards.py", line 44, in load
    act = deepq.build_act(**act_params)
  File "c:\users\rick\desktop\baselines\baselines\deepq\build_graph.py", line 146, in build_act
    observations_ph = make_obs_ph("observation")
  File "enjoy_mineral_shards.py", line 46, in make_obs_ph
    return U.BatchInput((64, 64), name=name)
AttributeError: module 'baselines.common.tf_util' has no attribute 'BatchInput'
W0204 12:41:43.175422 10984 sc_process.py:183] Killing the process.

**Comment by rwill128** [comment]
It seems like baseline is installed correctly. It's find the dependency in tf_util, but my version of tf_util has no such method called "BatchInput".

I looked in Git history for baselines, and that file appears to have never had a method called "BatchInput", which is puzzling to me.

**Comment by brean** [comment]
BatchInput was part of baselines/common/tf_util.py since its last cleanup-commit ([take a look at this change](https://github.com/openai/baselines/commit/9fa8e1baf1d1f975b87b369a8082122eac812eb1#diff-0812f033cfce941f940af3741c516200L118)). I guess it moved to baselines/deepq/utils.py (see [here](https://github.com/openai/baselines/commit/9fa8e1baf1d1f975b87b369a8082122eac812eb1#diff-f2b1c4930b29e29cc13b7a8fea4faa33R53))

**Comment by rwill128** [comment]
Thanks!

**Comment by moshebeutel** [comment]
hi
maybe this is related...

while trying to run train_mineal_shards.py I got



/home/iaiai/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/iaiai/pysc2-examples/train_mineral_shards.py", line 14, in <module>
    from a2c.policies import CnnPolicy
  File "/home/iaiai/pysc2-examples/a2c/policies.py", line 3, in <module>
    from baselines.acktr.utils import conv, fc, dense, conv_to_fc, sample, kl_div
ImportError: cannot import name 'conv'
