### ISSUE TITLE
TypeError: Can't instantiate abstract class SubprocVecEnv with abstract methods step_async, step_wait

### ISSUE THREAD

**Issue by okdolly** [chris-chris/pysc2-examples#14]
WARNING:tensorflow:From /Users/domore/Documents/deeplearning/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
algorithm : a2c
timesteps : 2000000
exploration_fraction : 0.5
prioritized : True
dueling : True
num_agents : 4
lr : 0.0005
random lr : 0.0005
Traceback (most recent call last):
  File "/Users/domore/starcraft/pysc2-examples/train_mineral_shards.py", line 302, in <module>
    main()
  File "/Users/domore/starcraft/pysc2-examples/train_mineral_shards.py", line 168, in main
    env = SubprocVecEnv(FLAGS.num_agents + FLAGS.num_scripts, FLAGS.map)
TypeError: Can't instantiate abstract class SubprocVecEnv with abstract methods step_async, step_wait

**Comment by woaipichuli** [comment]
I get the same problem.Have you solved it out yet?

**Comment by okdolly** [comment]
No, unfortunately.
