### ISSUE TITLE
when run python  enjoy_mineral_shards.py come with error

### ISSUE THREAD

**Issue by majichang** [chris-chris/pysc2-examples#18]
Hallo ,  when I run command "python  enjoy_mineral_shards.py" in terminal ,the error is:

Traceback (most recent call last):
File "enjoy_mineral_shards.py", line 163, in <module>
    main()
File "enjoy_mineral_shards.py", line 39, in main
    game_steps_per_episode=steps * step_mul) as env:
File "/home/m/.local/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 248, in __init__
    raise ValueError("Please specify agent_interface_format.")
ValueError: Please specify agent_interface_format.

Can anyone else can solve it ??? Thanks

**Comment by chauvinfish** [comment]
add
` agent_interface_format=sc2_env.AgentInterfaceFormat(
              feature_dimensions=sc2_env.Dimensions(
                screen=84,
                minimap=64))`
will solve the problem.
But then you will meet batchinput error,load_state error and key error 'screen'.
