### ISSUE TITLE
It seems dqn can't learn much

### ISSUE THREAD

**Issue by Seraphli** [chris-chris/pysc2-examples#2]
I ran the script last night. It started with ~11 mean reward, and ended with ~15.5 mean reward.
![Begin](https://user-images.githubusercontent.com/1586755/30090791-4a7e0c26-92e8-11e7-82db-685633a1d37d.png)
![End](https://user-images.githubusercontent.com/1586755/30090811-7a50a76a-92e8-11e7-81e8-0f8226b04a03.png)

**Comment by vors** [comment]
Kind of got a similar experience, but it actually dropped from 10 to 5 :D
Here is what the net learned on my laptop, marines are mostly hanging out at the bottom of the screen
![marines](https://user-images.githubusercontent.com/816680/30247179-e7183624-95c2-11e7-89eb-122190bed5ca.gif)

**Comment by chris-chris** [comment]
Yeah, guys. I'm trying to enhance the score using the A3C algorithm.
I'm re-writing the example codes.

If you have any improvement, please let me know! :)

**Comment by chris-chris** [comment]
I'm applying the A3C algorithm on it. This is the baseline agent of the paper.
https://deepmind.com/documents/110/sc2le.pdf

**Comment by vors** [comment]
Awesome! Will try it soon

**Comment by ShadowDancer** [comment]
@chris-chris How's going with A3C? I see you changed the principle, is it getting any better?

**Comment by chris-chris** [comment]
@Seraphli @ShadowDancer @vors @yilei 

I applied A2C algorithm. I think it works better.
you can train it with commands below.

```
python train_mineral_shards.py --algorithm=a2c --num_agents=2 --num_scripts=2 --timesteps=2000000
```

**Comment by Seraphli** [comment]
I tried to run the code, and at some point the program threw out this error.
```
Traceback (most recent call last):
  File "train_mineral_shards.py", line 304, in <module>
    main()
  File "train_mineral_shards.py", line 183, in main
    callback=a2c_callback)
  File "/home/seraphli/Github/pysc2-examples/a2c/a2c.py", line 748, in learn
    obs, states, rewards, masks, actions, xy0, xy1, values = runner.run()
  File "/home/seraphli/Github/pysc2-examples/a2c/a2c.py", line 621, in run
    self.update_obs(obs)
  File "/home/seraphli/Github/pysc2-examples/a2c/a2c.py", line 297, in update_obs
    marine1 = self.xy_per_marine[env_num]["1"]
KeyError: '1'
```

**Comment by davidkuhta** [comment]
I'm having the same `KeyError: '1'` issue as @Seraphli (output near identical to the above). Any idea where to look?

**Comment by chris-chris** [comment]
@davidkuhta @Seraphli I'll fix it! thanks!!

**Comment by chris-chris** [comment]
@davidkuhta @Seraphli I fixed it. Can you guys check it out?

**Comment by davidkuhta** [comment]
Thanks @chris-chris! Running it now, will follow-up

**Comment by davidkuhta** [comment]
Ok, still ran into the same issue, I did see the initialization in the last commit:
`self.xy_per_marine = [{"0":[0,0], "1":[0,0]} for _ in range(nenv)]`
I'm rerunning having added a print statement at **296** to output the `self.xy_per_marine[env_num]` dict.

**Comment by simonmeister** [comment]
Just in case you want to take a look at a similar work-in-progress A2C implementation: https://github.com/simonmeister/pysc2-rl-agents.

**Comment by simonmeister** [comment]
Just in case anyone would like to look at a alternative work-in-progress implementation without openai-baselines dependency and complete action space: https://github.com/simonmeister/pysc2-rl-agents.

**Comment by mushroom1116** [comment]
Is there anyone who has encountered this error?

TypeError: Can't instantiate abstract class SubprocVecEnv with abstract methods step_async, step_wait

**Comment by soneo1127** [comment]
@mushroom1116 I change the subproc_vec_env.py

> from baselines.common.vec_env import VecEnv

to

> from . import VecEnv

and can run.
