### ISSUE TITLE
ImportError: cannot import name 'mse'

### ISSUE THREAD

**Issue by Guo-Youtian** [chris-chris/pysc2-examples#22]
$ python train_mineral_shards.py --algorithm=a2c
/home/guoyoutian/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "train_mineral_shards.py", line 15, in <module>
    from a2c import a2c
  File "/home/guoyoutian/PycharmProjects/pysc2-examples-master/a2c/a2c.py", line 12, in <module>
    from baselines.a2c.utils import cat_entropy, mse
ImportError: cannot import name 'mse'

**Comment by XuJing1022** [comment]
Hi, I met the same bug. Whether did you solve it later? thx

**Comment by divyavanmahajan** [comment]
The baselines.a2c.util does not have a "mse" function. So edit a2c/a2c.py

Line 12: REMOVE mse
`from baselines.a2c.utils import cat_entropy **, mse**`

Line 27: Define the mse function
```
def mse(pred, target):
  return tf.square(pred-target)/2.
```
