### ISSUE TITLE
train_mineral_shards.py raises error.

### ISSUE THREAD

**Issue by haje01** [chris-chris/pysc2-examples#3]
I'm using Python 3.5.3 in macOS with following packages:    

    git+https://github.com/openai/baselines.git@699919f1cf2527b184f4445a3758a773f333a1ba#egg=baselines
    PySC2==1.1

When I run the command:

    $ python train_mineral_shards.py 

Error raises:

    Traceback (most recent call last):
      File "train_mineral_shards.py", line 51, in <module>
        main()
      File "train_mineral_shards.py", line 24, in main
        visualize=True) as env:
      File "/Users/haje01/.pyenv/versions/pysc2/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 128, in __init__
        raise ValueError("All arguments must be passed as keyword arguments.")
    ValueError: All arguments must be passed as keyword arguments.

Any ideas?

**Comment by entruv** [comment]
same problem !

**Comment by chris-chris** [comment]
Okay I'll check it out!

**Comment by yukang2017** [comment]
@haje01 @entruv 
In train_mineral_shards.py, 
modify line 22,
"CollectMineralShards",
 to be
map_name = "CollectMineralShards",

**Comment by chris-chris** [comment]
@yukang2017 fixed it! Thanks!

**Comment by yukang2017** [comment]
you are welcome. It's caused by the version of pysc2

**Comment by chengyao0929** [comment]
@chris-chris 
When I run the command:
$ python train_mineral_shards.py  --algorithm=acktr

Traceback (most recent call last):
  File "train_mineral_shards.py", line 5, in <module>
    from baselines import deepq
  File "/home/cy/anaconda2/lib/python2.7/site-packages/baselines/deepq/__init__.py", line 4, in <module>
    from baselines.deepq.simple import learn, load  # noqa
  File "/home/cy/anaconda2/lib/python2.7/site-packages/baselines/deepq/simple.py", line 10, in <module>
    from baselines import logger
  File "/home/cy/anaconda2/lib/python2.7/site-packages/baselines/logger.py", line 140
    def log(*args, level=INFO):
                       ^
SyntaxError: invalid syntax

Do you know how to fix it？ I used python2.7，should l use python3.5？
